Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "ParaStationMPI/5.8.0-1"
   Try: "module spider ParaStationMPI/5.8.0-1" to see how to load the
module(s).



Lmod has detected the following error: These module(s) exist but cannot be
loaded as requested: "mpi4py/3.0.3-Python-3.8.5"
   Try: "module spider mpi4py/3.0.3-Python-3.8.5" to see how to load the
module(s).



Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
    from mpi4py import MPI
    from mpi4py import MPI
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
ModuleNotFoundError: No module named 'mpi4py'
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
ModuleNotFoundError: No module named 'mpi4py'
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
Traceback (most recent call last):
  File "/p/home/jusers/lam1/deep/proj/mpi.py", line 5, in <module>
    from mpi4py import MPI
ModuleNotFoundError: No module named 'mpi4py'
srun: error: dp-cn01: tasks 0-2,4-6: Terminated
srun: error: dp-cn01: tasks 3,7: Exited with exit code 1
srun: Force Terminated StepId=344128.0
